### PR TITLE
enhancement/coaccusals

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
@pckhoi the process-data check is failing at the `wrgl pull` stage. Error is below. Please advise.

```
Run wrgl config set --global user.email "gh-action@publicdata.works"
##[debug]/usr/bin/bash -e /runner/_work/_temp/83499354-cdec-448a-8073-6a8e7108beaf.sh
mkdir: cannot create directory '/runner/_work/data/.wrgl': File exists
mkdir /runner/_work/data/.wrgl/kv: file exists
common ancestor commit not found
Error: Process completed with exit code 1.
```

**Comment by pckhoi** [comment]
The data is corrupted somehow. Let me inspect over the weekend okay?

**Comment by ayyubibrahimi** [comment]
Perfect. Thanks.

**Comment by ayyubibrahimi** [comment]
Thanks @pckhoi

**Comment by pckhoi** [comment]
@ayyubibrahimi please prioritize the ocr pr next, it's not great to have it open for so long.

Also I might have forgot to decrease log verbosity.

**Comment by ayyubibrahimi** [comment]
You mean PR #408? I didn't realize I was supposed to be working on it. Sorry. Will review.

**Comment by pckhoi** [comment]
Please merge this PR and then I'll update GH action runner to process that PR.

**Pull request merged**
