### PR TITLE
bug/canoncicals

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by pckhoi** [comment]
So looks like it is trying to queue pdf for OCR, which isn't supposed to happen. All OCR queueing should be done locally. Can you `dvc pull` and `make` again? I think there are some metadata outputs that are outdated.

**Comment by ayyubibrahimi** [comment]
On it.

**Comment by ayyubibrahimi** [comment]
Hm. I just attempted to re-`dvc push` the file `post_officer_history_3.model` but it seems that everything is up to date. Will look into it further.

**Comment by ayyubibrahimi** [comment]
You should be able to run `make` now without an `error`.

**Comment by pckhoi** [comment]
Saw this during `make`:
```
make: Circular data/fuse/personnel_pre_post.csv <- data/match/post_officer_history.csv dependency dropped.
make: Circular data/fuse/allegation.csv <- data/fuse/allegation.csv dependency dropped.
make: Circular data/fuse/event_pre_post.csv <- data/fuse/event_pre_post.csv dependency dropped.
make: Circular data/fuse/event_pre_post.csv <- data/fuse/personnel_pre_post.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/use_of_force.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/match/post_officer_history.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/allegation.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/event_pre_post.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/personnel_pre_post.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/use_of_force.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/match/post_officer_history.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/allegation.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/event_pre_post.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/personnel_pre_post.csv dependency dropped.
make: Circular data/fuse/use_of_force.csv <- data/fuse/use_of_force.csv dependency dropped.
```
I think the `fuse/post_officer_history.py` script is problematic. I saw it both read and write to `fuse/use_of_force.csv`. Perhaps this file should be in another stage altogether.Basically we want all the dependency to form a directed acyclic graph (DAG). Drawing out the dependency in a graph application like draw.io could help.

**Comment by pckhoi** [comment]
Even if it's not causing problem right now it might not produce the results that you think it is.

**Comment by ayyubibrahimi** [comment]
Thanks for the reminder. We discussed the `fuse/post_officer_history.py` script a while ago as a temporary solution. Agreed that it's time to find a permanent solution. I'll begin making those changes.

**Comment by ayyubibrahimi** [comment]
Apologies if you ran into another error. `make` should now run without error on your end.

**Comment by pckhoi** [comment]
Do you need me to look at the error over the weekend?

**Comment by ayyubibrahimi** [comment]
That would be great. The new process-data error is:

```
Traceback (most recent call last):
      File "/runner/_work/processing/processing/ocr/post_officer_history_reports_2023_rotated.py", line 20, in <module>
        df23_rotated = process_pdfs_2023_rotated()
      File "/runner/_work/processing/processing/ocr/post_officer_history_reports_2023_rotated.py", line 13, in process_pdfs_2023_rotated
        pd.read_csv(deba.data("meta/post_officer_history_reports_2023_rotated_files.csv"))
      File "/home/runner/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 5512, in pipe
        return com.pipe(self, func, *args, **kwargs)
      File "/home/runner/.local/lib/python3.9/site-packages/pandas/core/common.py", line 497, in pipe
        return func(obj, *args, **kwargs)
      File "/runner/_work/processing/processing/lib/ocr.py", line 224, in process_pdf
        df = _enqueue_pdf(df, dir_name, requeue, requeue_unsuccessful)
      File "/runner/_work/processing/processing/lib/ocr.py", line 148, in _enqueue_pdf
        queue_pdf_for_ocr.run([str(tmpdir)])
      File "/runner/_work/processing/processing/lib/queue_pdf_for_ocr.py", line 56, in run
        subprocess.run(
      File "/usr/lib/python3.9/subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gsutil'
make: *** [.deba/deps/ocr.d:25: /runner/_work/data/data/ocr/post_officer_history_reports_2023_rotated_pdfs.csv] Error 1
```

And on my local I receive a WRGL error:

```
md5sum fuse/cross_agency.py > .deba/md5/fuse/cross_agency.py.md5
key not found
key not found
make: *** [wrgl.mk:4: pull_person] Error 1
```

I'll continue to attempt to debug. Thanks!

**Comment by pckhoi** [comment]
I ran everything fine on local. Can you run `wrgl pull --all` and show me the output?

**Comment by ayyubibrahimi** [comment]
Thanks Khoi. Below is the error returned when I run `wrgl pull --all`

`error fetching objects: error poping haves: GetCommit 2b6c52f53a18e0f0b232b63fddefa475 error: key not found`

**Comment by pckhoi** [comment]
Just run it again and again until it succeed. I reckon there's a bug but for now it's not so serious that you cannot proceed.

**Pull request closed without merging**
