### PR TITLE
enhancement/post-officer-histories

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
Hi @baoea. Please review the error at the process-data step. I've been getting it over the past week. Do you know if anything changed with the credentials when writing the validator? Thanks!

**Comment by baotvdn** [comment]
Hi @ayyubibrahimi. This error has nothing to do with the validator. The validator doesn't touch any credential in the repo because it is from external repo.

It said "google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/k8s-ocr-jobqueue-pdfs/o?maxResults=1&projection=noAcl&prefix=ocr%2F60%2F0ca6bd1d2a31bd2be9dbb11cc8b337b3feefd4&prettyPrint=false: Caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist)"

Might be you should check `k8s-ocr-jobqueue-pdfs` on the cloud storage, or check the permission of that folder.
Thanks!

**Comment by baoea** [comment]
Hi @ayyubibrahimi. This error has nothing to do with the validator. The validator doesn't touch any credential in the repo because it is from external repo.

It said "google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/k8s-ocr-jobqueue-pdfs/o?maxResults=1&projection=noAcl&prefix=ocr%2F60%2F0ca6bd1d2a31bd2be9dbb11cc8b337b3feefd4&prettyPrint=false: Caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist)"

Might be you should check `k8s-ocr-jobqueue-pdfs` on the cloud storage, or check the permission of that folder.
Thanks!

**Comment by ayyubibrahimi** [comment]
Thanks for the update.

**Pull request merged**
