### PR TITLE
Enhancement/appeal and sas field names

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by pckhoi** [comment]
@ayyubibrahimi do you see this error on your local?
```bash

running ner/post_officer_history_reports.py
    /Users/khoipham/.virtualenvs/base/lib/python3.9/site-packages/spacy/util.py:837: UserWarning: [W095] Model 'en_pipeline' (0.0.0) was trained with spaCy v3.2 and may not be 100% compatible with the current version (3.3.1). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
      warnings.warn(warn_msg)
    Traceback (most recent call last):
      File "/Users/khoipham/projects/PPACT/ner/post_officer_history_reports.py", line 40, in <module>
        ner21 = apply_spacy_model(pdfs_21, trained_model)
      File "/Users/khoipham/projects/PPACT/lib/ner.py", line 61, in apply_spacy_model
        for row in df["text"].apply(nlp):
      File "/Users/khoipham/.virtualenvs/base/lib/python3.9/site-packages/pandas/core/series.py", line 4433, in apply
        return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
      File "/Users/khoipham/.virtualenvs/base/lib/python3.9/site-packages/pandas/core/apply.py", line 1082, in apply
        return self.apply_standard()
      File "/Users/khoipham/.virtualenvs/base/lib/python3.9/site-packages/pandas/core/apply.py", line 1137, in apply_standard
        mapped = lib.map_infer(
      File "pandas/_libs/lib.pyx", line 2870, in pandas._libs.lib.map_infer
      File "/Users/khoipham/.virtualenvs/base/lib/python3.9/site-packages/spacy/language.py", line 1008, in __call__
        doc = self._ensure_doc(text)
      File "/Users/khoipham/.virtualenvs/base/lib/python3.9/site-packages/spacy/language.py", line 1102, in _ensure_doc
        raise ValueError(Errors.E1041.format(type=type(doc_like)))
    ValueError: [E1041] Expected a string, Doc, or bytes as input, but got: <class 'float'>
```

**Comment by pckhoi** [comment]
Ever since I updated my mac last night a bunch of weird things happened. This could be one of the results.

**Comment by pckhoi** [comment]
So I dig deeper into the script `ner/post_officer_history_reports.py` and I see a couple odd things:
1. There are 712 rows with NA text vs 115 rows with non-NA text from `pdfs_21`. This leads to the above spacy error. Was it always like this? Can you double check on your local?
2. `pdfs_22` doesn't have a `text` column, yet it is fed into `apply_spacy_model` regardless. If it wasn't failing then it should from now on.

**Comment by ayyubibrahimi** [comment]
@pckhoi Thanks for looking into `ner/post_officer_history_reports.py`

1. Are you referring to `pdfs_22`? There is no `pdfs_21` currently. If so, I have 0 rows with NA text vs 428 rows with non-NA text. 
2. `pdfs_22` has a text column

**Comment by pckhoi** [comment]
So looks like it was the result of ocr results being half-finished. Retrying with ocr job finished seems to work great!

**Comment by pckhoi** [comment]
Sure, give it a go.

**Pull request merged**
