### PR TITLE
[f] 654 - Implement enhanced data pipeline flow

### PR DESCRIPTION
**Pull request by baoea**
[#184334654](https://www.pivotaltracker.com/story/show/184334654)

The web team would like to add schema validator to github action. The validating job will run after the transaction is applied.

Thanks!

### CODE REVIEW

**Comment by baoea** [comment]
Close this PR due to missing KEYCLOAK_CLIENT_SECRET

**Comment by baoea** [comment]
Hi @ayyubibrahimi and @rajivsinclair, the workflow failed because it could not get the secrets from the `main` repository. You can find it [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) for information. Besides, my code does not use any secret from the project. There are two solutions for us:
- Ayyub takes a look at the commit, and merge the code
- Ayyub grants us a permission to push and access the secret. So my PR can get access to the secret.

Thanks!

**Comment by ayyubibrahimi** [comment]
@baoea Hi Bao, I've invited you to be a maintainer of the repo, which should allow you to push to the repo.

**Comment by baoea** [comment]
Thanks @ayyubibrahimi

**Comment by baoea** [comment]
Close this PR because of the new one

**Pull request closed without merging**
