### PR TITLE
Enhancement/baton rouge pd settlements

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
Hey @pckhoi.  After some investigation, I don't believe this is due to a local error.  Please advise re the process-data failure. Thanks!

**Comment by pckhoi** [comment]
There's probably a phantom (non-existent) branch somewhere. I'll try to get back on this before Thursday.

**Comment by ayyubibrahimi** [comment]
Awesome. Whenever you can is perfect. Thanks.

**Comment by pckhoi** [comment]
@ayyubibrahimi I found this snippet, no wonder it doesn't work.
```yaml
  post-officer-history:
    remote: origin
    merge: refs/heads/post_officer_history
    file: data/fuse/post_officer_history.csv
    primaryKey:
      - uid
```

The correct remote ref is `refs/heads/post-officer-history`: https://hub.wrgl.co/@ipno/r/data/refs/heads/post-officer-history

I ran `wrgl pull --all` on local and was able to reproduce. Did you not see this error on local?

**Comment by ayyubibrahimi** [comment]
My terminal kept crashing when I ran it. It looks like that was a fault on my end because of the poor wifi at the airport. Apologies.

**Comment by pckhoi** [comment]
`stream error: stream ID 19; PROTOCOL_ERROR;` is a temporary network error I think. Retrying should work in that case. And you don't have to re-download all the blocks that you have so it should be relatively quick.

That said, I'm making some tweaks before releasing v0.12.3. Please wait until that version is ready.

**Comment by pckhoi** [comment]
Hold on. Fixing some output issues.

**Comment by ayyubibrahimi** [comment]
Got it.

**Comment by pckhoi** [comment]
@ayyubibrahimi I have made some tweaks and the workflow is working beautifully now. Also, please install the latest wrgl version. It should be v0.12.7.

Also from now on, if the branch name does not match `merge` key then wrgl commit will fail.

**Comment by ayyubibrahimi** [comment]
Awesome. Thanks @pckhoi !

**Pull request merged**
