### PR TITLE
enhancement/benton_pd_cprr

### PR DESCRIPTION
**Pull request by ayyubibrahimi**

### CODE REVIEW

**Comment by ayyubibrahimi** [comment]
Hey @pckhoi. I'm running into an issue with dvc at the `process-data` check. I don't believe that there is an issue with space on my end, but rather with dvc. Please let me know if I'm wrong. Thanks!

**Comment by pckhoi** [comment]
The persistent volume literally ran out of disk space. I have just doubled its size. Should work okay now.

**Comment by ayyubibrahimi** [comment]
Cool. That's what I figured but I wanted to be sure before asking you for your time. Thanks!

**Comment by pckhoi** [comment]
If you're comfortable with k8s, here's the script that I used to quickly check the disk:
```bash
scripts/kubectl-run-with-pvc.sh -n cdi-runner cdi-runner-data
```

**Comment by ayyubibrahimi** [comment]
More comfortable, but still still learning. Thanks.

**Comment by ayyubibrahimi** [comment]
@pckhoi Hey Khoi, I hope everything is going well. The persistent volume literally ran out of disk space again. I'm having some issues with doubling it myself. If you have the capacity, would it be possible for you to double it?

**Pull request merged**
